### ISSUE TITLE
Conflicting results from "shapes_in_area" and "contains_point"

### ISSUE THREAD

**Issue by minusdavid** [shawnlaffan/Geo-ShapeFile#33] opened 2023-08-07 05:28 UTC
Overall, the library works great. Thanks for staying active on it!

I'm creating a point using Geo::ShapeFile::Point and then feeding in the x_min, y_min, x_max, and y_max into $shapefile->shapes_in_area. It returns very quickly but it returns 1 more shape than I expected (for a total of 2 shapes).

If I loop through all the shapes using $shapefile->shapes() and call $shape->contains_point($point), I only get the 1 shape. 

When I load the shapefile into QGIS and search for the coordinates in the status bar, I'm just getting the 1 shape. In QGIS, I can select the 2nd shape via the attribute table but I can't see it on the map. 

I imagine that I'm missing something obvious but I'm not sure what it is. 

$shapefile->shapes_in_area is much faster than iterating through all the shapes, so for now I'm using that method plus running $shape->contains_point($point) as a double-check to weed out the shape I don't need. 

Any thoughts on what might be going on? Happy to share more information if that's helpful. The shapefile is open data so nothing private there.

**Comment by shawnlaffan** [comment] 2023-08-07 06:57
It could be something odd with the input shapefile, although two entries in the attribute table suggests coincident features.

Can you share the data?  You should be able to attach a zip file to a comment in GitHub if it is not too large.  

The code would also be useful for reproduction.

**Comment by minusdavid** [comment] 2023-08-07 07:01
I just noticed that you're from UNSW. The data set is actually for NSW electorates. 

https://data.gov.au/data/dataset/8047ddd1-7193-4667-aef9-b75bc3076075/resource/7e2a7fe0-5d77-400e-8f9c-1f47b460c930/download/nsw_eb_gda94.zip

I'll write up a code snippet tomorrow to show you what I mean.

**Comment by shawnlaffan** [comment] 2023-08-07 07:08
Thanks for the link.  If you let me know the polygon IDs then I can have a look.

**Comment by shawnlaffan** [comment] 2023-08-07 07:47
The file contains many duplicated polygons.  For example NSW220 and NSW221 (SE_PID field) appear to be coincident and span the full NSW extent.  

Clicking on any polygon generally returns four polygons for each point - the two NSW polygons and 2015 and 2023 versions.  Some polygons have also been subdivided in 2023 (e.g. NSW151 is split into NSW377 and NSW389).  

I used ArcGIS Pro but it should be replicable using QGIS.  

We still need to check that Geo::Shapefile is getting the correct polygons for each operation, for which the code will help.

**Comment by minusdavid** [comment] 2023-08-08 00:04
If you look in NSW_STATE_ELECTORAL_shp.dbf, there's additional metadata that you can link using the SE_PID. 

So NSW220 and NSW221 both refer to "LEGISTLATIVE COUNCIL" but NSW221 is no longer in effect while NSW220 is since it takes over from NSW221. (I don't know why they'd bother with this polygon though since it's all encompassing. Fortunately, I can ignore it in my processing as it has a SECL_CODE of 3 while the others have a SECL_CODE of 2.)

I'll do that code snippet up now to explain the discrepancy I'm noticing though.

**Comment by minusdavid** [comment] 2023-08-08 00:37
Here's the output I'm getting. I'll post the code shortly. 

Finding point -33.8825921,151.1784643
Get shapes using 'shapes_in_area()'
Name: BALMAIN | SE_PLY_PID 2544 | SE_PID: NSW359
$VAR1 = {
          'DT_RETIRE' => '',
          'EFF_END' => '',
          'STATE_PID' => '1',
          'SE_PID' => 'NSW359',
          'NAME' => 'BALMAIN',
          'DT_GAZETD' => '20210826',
          '_deleted' => '',
          'DT_CREATE' => '20211112',
          'EFF_START' => '20230325',
          'SECL_CODE' => 2
        };
Name: NEWTOWN | SE_PLY_PID 2631 | SE_PID: NSW329
$VAR1 = {
          'EFF_END' => '',
          'DT_RETIRE' => '',
          'STATE_PID' => '1',
          'SE_PID' => 'NSW329',
          'NAME' => 'NEWTOWN',
          '_deleted' => '',
          'DT_GAZETD' => '20210826',
          'EFF_START' => '20230325',
          'DT_CREATE' => '20211112',
          'SECL_CODE' => 2
        };
Iterate through all shapes
Name: BALMAIN | SE_PLY_PID 2544 | SE_PID: NSW359
$VAR1 = {
          'DT_RETIRE' => '',
          'EFF_END' => '',
          'STATE_PID' => '1',
          'SE_PID' => 'NSW359',
          'NAME' => 'BALMAIN',
          'DT_GAZETD' => '20210826',
          '_deleted' => '',
          'DT_CREATE' => '20211112',
          'EFF_START' => '20230325',
          'SECL_CODE' => 2
        };

**Comment by minusdavid** [comment] 2023-08-08 00:39
Using QGIS, it looks like the point -33.8825921,151.1784643 should fall around the bottom of the BALMAIN polygon, so I'm not sure why shapes_in_area() is getting NEWTOWN as well, since that's further south.

**Comment by minusdavid** [comment] 2023-08-08 00:41
[geo_snippet.zip](https://github.com/shawnlaffan/Geo-ShapeFile/files/12286065/geo_snippet.zip)

**Comment by minusdavid** [comment] 2023-08-08 00:43
I've had the same thing happen for other points a bit further East. 

At the moment, my workaround is to use "shapes_in_area()" to get a smaller set of shapes (since it's a very fast function) and then to iterate through those and use "contains_point()" on each shape to determine if the point really is in that shape. 

It's effective, but I thought I'd share my findings with you, since "shapes_in_area()" seems a bit off...

**Comment by shawnlaffan** [comment] 2023-08-08 08:14
Thanks for providing the code.  

The ```shapes_in_area``` method checks which feature envelopes overlap.  It is not a full point in polygon search since a feature envelope is just the bounding box of its geometry.  Sorry for not noticing when the issue was first raised.  

```shapes_in_area``` can be used as a first pass filter to get a smaller set of candidate polygons to then pass through the more involved ```contains_point``` method.  

FWIW, spatial indexing methods typically use the envelopes (see for example [Tree::R](https://metacpan.org/pod/Tree::R) if you need a perl implementation).  

The method would ideally be renamed to be more informative but it has been this way since long before I took over maintenance of this module.  I could always add an alias, though.

**Comment by minusdavid** [comment] 2023-08-08 23:31
After reading your comment and re-reading the documentation, it all makes sense now. I'm very new to GIS, so I thought it was probably me just misunderstanding, but thought that I would double-check just in case.

When I load it up in QGIS (and especially when I add a bounding box layer), I can see the overlapping bounding boxes. 

I don't think you need to change anything. I probably should've done more research into GIS ahead of time. Happy to close this one off.

**Comment by shawnlaffan** [comment] 2023-08-09 01:04
Not a problem.  Good to hear it's all sorted now.

I'll close this issue now but feel free to report anything else that seems amiss.

**Closed as completed by shawnlaffan** 2023-08-09 01:04 UTC
